version: 0.2

# 下記はcode buildに追加する必要があるらしい
# teraformで設定もできる
# AWS_REGION
# AWS_ACCOUNT_ID

# todo 事前にリポジトリ作成必要あり

# コマンドでも作成できる
# aws ecr create-repository \
#   --repository-name go-api \
#   --region ap-northeast-1
# resource "aws_ecr_repository" "go_api" {
#   name = "go-api"
# }

phases:
  pre_build:
    commands: # ecrにログインしてる
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - docker build -t terraform-go-api .
      - docker tag terraform-go-api:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/terraform-go-api:latest
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/terraform-go-api:latest
      - printf '[{"name":"terraform-go-api","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/terraform-go-api:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
